export const HOBBIES = [
  "Reading",
  "Writing",
  "Cooking",
  "Baking",
  "Hiking",
  "Swimming",
  "Cycling",
  "Jogging",
  "Yoga",
  "Meditation",
  "Painting",
  "Drawing",
  "Photography",
  "Gardening",
  "Fishing",
  "Gaming",
  "Traveling",
  "Music",
  "Dancing",
  "Singing",
  "Chess",
  "Knitting",
  "Woodworking",
  "Pottery",
  "Crafting",
  "Astronomy",
  "Bird watching",
  "Collecting",
  "Skateboarding",
  "Surfing",
  "Rock climbing",
  "Tennis",
  "Golf",
  "Basketball",
  "Soccer",
  "Volunteering",
  "Learning languages",
  "Podcasting",
  "Blogging",
  "DJing",
  //  Lol, Don't judje me please
  "Vibecoding",
];
